### ISSUE TITLE
End-to-end implementation user entity

### ISSUE THREAD

**Issue by mcherny** [aquasecurity/terraform-provider-aquasec#1]
"end-to-end" means code, unit tests, acceptance tests, documentation and submission to terraform registry.

Few notes:

- The repo code is just for reference. Please make it right as you see fit.
- The github.com/BryanKMorrow/aqua-sdk-go/client referenced from the code is also for reference and if used must be copied to project and refactored as needed.

**Comment by BryanKMorrow** [comment]
README is missing some steps. It mentions running `go install` but the actual provider is built in the Makefile, so without running `make install` the provider will not be built, just the executable that the provider runs.
