### ISSUE TITLE
Provider authentication to Aqua SaaS not working

### ISSUE THREAD

**Issue by sigurdfalk** [aquasecurity/terraform-provider-aquasec#100]
Hi!

Tested the new version of the Terraform provider today, but unfortunately, we are still having issues using the provider with our Aqua SaaS solution. The reason is the same as described in this comment in the PR: https://github.com/aquasecurity/terraform-provider-aquasec/pull/93#discussion_r833143771.
 
More details:
 
As you can see here https://github.com/aquasecurity/terraform-provider-aquasec/blob/main/client/client.go#L53-L60, client type for our login is set to SaaS, which makes sense. However, when getting the token for login here https://github.com/aquasecurity/terraform-provider-aquasec/blob/main/client/client.go#L68-L72, SaaS clients are using login with “email” and “password”, rather than “id” and “password” as shown here https://github.com/aquasecurity/terraform-provider-aquasec/blob/main/client/client.go#L108-L112. This makes the provider fail with the following message on initialization when we try to sign in with a user created in the Aqua SaaS Console:

```json 
{
  "status": 422,
  "code": 1,
  "message": "Invalid request",
  "errors": [
   {
     "field": "data.email",
     "message": "pattern mismatch",
     "value": "terraform",
     "type": "string",
     "schemaPath": [
      "properties",
      "email"
     ]
   }
  ]
}
```

### Expected Behavior

Provider should be able to login to Aqua SaaS and create resources with Terraform.

### Actual Behavior

Provider fails at login step.

### Steps to Reproduce

1) Create a user in Aqua SaaS Console with "Administrator" rights
2) Use username and password for this user in the `aquasec` provider block

### References

We had a hope that https://github.com/aquasecurity/terraform-provider-aquasec/pull/93 would solve our issues, but this was not the case

**Comment by semyonmor** [comment]
@sigurdfalk 
Can you pls send me by email the example of how exactly you tried to use the provider? Which user did you use for it? 
Semyon.mor@aquasec.com

**Comment by sigurdfalk** [comment]
Sent @semyonmor :)
