### ISSUE TITLE
Terraform provider with SSO enabled

### ISSUE THREAD

**Issue by ggmoy** [aquasecurity/terraform-provider-aquasec#103]
Hi there,

Is it possible to use this terraform provider having Google SSO? I can't provide user/password when SSO is enabled.

Could anyone help me, please?

Thanks!

**Comment by semyonmor** [comment]
Hi @ggmoy 

Unfortunetly currently we are not supporting the SSO for terraform provider.
You can create the service account that will be used for provider actions only and other users will continue to use the SSO.
IF you need more details pls take it with Aqua Support
