### ISSUE TITLE
Remove unused Enforcer Group fields causing potential confusion

### ISSUE THREAD

**Issue by davidrosson** [aquasecurity/terraform-provider-aquasec#105]
The `EnforcerGroup` struct (in the file `client/enforcers.go`) defines the request and response format for an Enforcer Group (via the `hostsbatch` API call to the Aqua Server). Currently, this struct includes the following line of code:
```
NetworkActivityProtection                 bool                 `json:"network_activity_protection"` 
```
However, a call to the `hostsbatch` API does not actually return any JSON result for the key `network_activity_protection`. Since this unused field is very similar to `network_protection` and `host_network_protection` (both of which _are_ used), this can lead to confusion.

To reduce the likelihood of misuse/confusion, all references to `NetworkActivityProtection` and `network_activity_protection` should be removed from Enforcer Group-related type definitions and functions.

Similarly, there is an unnecessary inclusion of `hostname` in the `schema.Resource` object returned by the function `resourceEnforcerGroup` (in the file `aquasec/resource_enforcer_group.go`), which should also be removed.

**Comment by semyonmor** [comment]
Fixed by #117
