### ISSUE TITLE
Certain Enforcer Group 'Set' parameters are mis-matched

### ISSUE THREAD

**Issue by davidrosson** [aquasecurity/terraform-provider-aquasec#106]
There are several cases for Enforcer Group parameters where the `key` and `value` passed to the `ResourceData` struct's `Set` method are not aligned (likely via copy/paste errors when duplicating code snippets); that is, the wrong referenced value (obtained via a `GetEnforcerGroup` call to the `hostsbatch` API) is used to set the value associated with the specified `ResourceData` object's key.

For example, `r.ContainerAntivirusProtection` is used to set the value of the key `container_activity_protection` for the `ResourceData` object `d` (this key's source value should actually come from `r.ContainerActivityProtection`).

In this collection of `Set` calls, there is also a duplicate case of `type` being set, which should be removed.

### Expected Behavior
Each `ResourceData` object's key should have its value set by its corresponding _actual_ value, retrieved via a `GetEnforcerGroup` call to the `hostsbatch` API.

### Actual Behavior
In those cases where parameters are mis-matched, the value of a `ResourceData` object can be incorrectly set via an update to an unrelated parameter. For example, the `auto_discover_configure_registries` key is currently being set by the value of `r.AllowKubeEnforcerAudit`, instead of by `r.AutoDiscoverConfigureRegistries`.

### Identified Enforcer Group parameter mis-matches
The following entries in the `resourceEnforcerGroupRead` function (in the file `aquasec/resource_enforcer_group.go`) contain errors and should be corrected, as shown:
```
From: d.Set("container_activity_protection", r.ContainerAntivirusProtection)
To:   d.Set("container_activity_protection", r.ContainerActivityProtection)
```
```
From: d.Set("host_behavioral_engine", r.BehavioralEngine)
To:   d.Set("host_behavioral_engine", r.HostBehavioralEngine)
```
```
From: d.Set("host_protection", r.HostNetworkProtection)
To:   d.Set("host_protection", r.HostProtection)
```
```
From: d.Set("auto_discover_configure_registries", r.AllowKubeEnforcerAudit)
To:   d.Set("auto_discover_configure_registries", r.AutoDiscoverConfigureRegistries)
```
```
Duplicate to remove: d.Set("type", r.Type)
```
Similarly, the following entries in the `dataEnforcerGroupRead` function (in the file `aquasec/data_enforcer_group.go`) contain errors and should be corrected, as shown (these actually mirror the errors present in the `resourceEnforcerGroupRead` function):
```
From: d.Set("container_activity_protection", group.ContainerAntivirusProtection)
To:   d.Set("container_activity_protection", group.ContainerActivityProtection)
```
```
From: d.Set("host_behavioral_engine", group.BehavioralEngine)
To:   d.Set("host_behavioral_engine", group.HostBehavioralEngine)
```
```
From: d.Set("host_protection", group.HostNetworkProtection)
To:   d.Set("host_protection", group.HostProtection)
```
```
From: d.Set("auto_discover_configure_registries", group.AllowKubeEnforcerAudit)
To:   d.Set("auto_discover_configure_registries", group.AutoDiscoverConfigureRegistries)
```
```
Duplicate to remove: d.Set("type", group.Type)
```

**Comment by semyonmor** [comment]
Fixed by #117
