### ISSUE TITLE
Unable to set an Enforcer Group's 'host_os' value

### ISSUE THREAD

**Issue by davidrosson** [aquasecurity/terraform-provider-aquasec#107]
### Limitation
Currently, the parameter `host_os` cannot be set when creating an Enforcer Group (via an `aquasec_enforcer_groups` resource), since it is defined as a `Computed` parameter rather than an `Optional` parameter. When an Enforcer Group is created without a "Host OS" value having been specified, it defaults to `Linux` (allowed values, when creating via the UI, are `Linux` and `Windows`). The inability to explicitly set the parameter `host_os` in the configuration means that only `Linux` Enforcer Groups can currently be created via the provider.

### Suggestion
It is possible to enable the ability to explicitly set the parameter `host_os`, while also accounting for the fact that it may be omitted from the configuration (and therefore receive a default value from the Aqua Server; no default needs to be set within the provider code). Per the `terraform-plugin-sdk` package, it is possible to set both `Computed` **_and_** `Optional` at the same time (ref: https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.14.0/helper/schema/schema.go#L41-L43). The result is that the `Optional` value will be used (if provided), and if not provided, then a default value will be `Computed` by the Aqua Server instead (which is currently `Linux`). This behavior prevents the enablement of `host_os`-specification from being a breaking change.

The function `resourceEnforcerGroupUpdate` is already using the `HasChanges` method to check whether the parameter `host_os` has been changed. Also, the `expandEnforcerGroup` function already includes a code block that updates `enforcerGroup.HostOs` by executing `d.GetOk("host_os")`, so most of the functionality needed for allowing the parameter `host_os` to be set is already in place.

An important consideration when updating the `host_os` specification in the `resourceEnforcerGroup` `Schema` is to also specify `ForceNew: true`. This is necessary because `Linux` and `Windows` Enforcer Groups require a slightly different collection of inputs and generate fundamentally different outputs, so converting an existing resource from one "Host OS" type to another isn't possible; in order to reuse the same `group_id` for a resource that is switching "Host OS" type, the resource must be replaced.

Finally, to ensure that only valid "Host OS" values are accepted by the provider, the `ValidateFunc` field can be specified in the `resourceEnforcerGroup` `Schema`, in which validation can be performed on the input value of `host_os` (accepting only `Linux` or `Windows` as valid input).

**Comment by semyonmor** [comment]
Fixed by #117
