### ISSUE TITLE
No description for the parameters of the aquasec_enforcer_groups resource

### ISSUE THREAD

**Issue by violiveira** [aquasecurity/terraform-provider-aquasec#109]
On the documentation for the **aquasec_enforcer_groups** resource, there are no description for the parameters.

Although some of the parameters are obvious, some of them are not. For example, what does group `group_id` mean?

It would be helpful to describe each of the parameters and ideally provide some examples of use.

**Comment by semyonmor** [comment]
Hey @violiveira 
We will update the documentation in the next release

**Comment by violiveira** [comment]
Thanks @semyonmor 

At the moment I am trying to understand why the parameters:

- host_os
- runtime_type

Are now considered Computed attributes:

`Computed attributes cannot be set, but a value was set for "runtime_type".`

The documentation shows these parameters as optional, so that is confusing.

**Comment by yossig-aquasec** [comment]
@violiveira sorry for that, we will add description with the next release. These parameters are only relevant for aqua enforcer (agent) for the other enforcer types they are set automatically (computed).
You can see their explanation in here:
https://docs.aquasec.com/docs/aqua-enforcer-groups-and-settings

**Comment by yossig-aquasec** [comment]
@violiveira sorry for that, we will add description with the next release. These parameters are only relevant for aqua enforcer (agent) for the other enforcer types they are set automatically (computed).
You can see their explanation in here:
https://docs.aquasec.com/docs/aqua-enforcer-groups-and-settings

**Comment by violiveira** [comment]
Dear @yossig-aquasec  thanks for your reply.

But it is the Aqua Enforcer itself that I am trying to deploy. If I set `type=agent` and the parameters `host_os` and `runtime_type`, the provider will throw the errors above. Please see the entire code below.

Will the aqua enforcer work if I don't provide these parameters?

```
resource "aquasec_enforcer_groups" "aqua-enforcer" {
  group_id = "aqua-enforcer"
  type = "agent"
  host_os = "Linux"
  orchestrator {
    type = "kubernetes"
    master = false
  }
  runtime_type = "containerd"
  logical_name = "aqua-enforcer"
  gateways = [ "aqua-gateway-domain" ]

  enforce = false

  image_assurance = true
  container_activity_protection = true
  network_protection = true
  user_access_control = false
  container_antivirus_protection = false

  host_assurance = true
  host_protection = true
  host_network_protection = true
  host_user_protection = false
  antivirus_protection = false

  sync_host_images = true
  risk_explorer_auto_discovery = true
}
```

**Comment by yossig-aquasec** [comment]
Thanks, will check it and update you

**Comment by yossig-aquasec** [comment]
@violiveira can you please update to version 0.8.10 and check again please
We added fixes to the enforcer group there.

**Comment by violiveira** [comment]
Hi @yossig-aquasec, I still face the errors:

`Computed attributes cannot be set, but a value was set for "host_os".`

`Computed attributes cannot be set, but a value was set for "runtime_type".`

if I try to configure any of these parameters for the aqua enforcer (type agent).

Maybe is it the API that has changed and now `host_os` and `runtime_type` are dynamically computed on the enforcer side?

**Comment by violiveira** [comment]
Hi @yossig-aquasec thanks for working on this.

The issue with parameters `host_os` and `runtime_type` seems to be fixed, thank you.

But since the original issue is about lack of description for the parameters and the description has not been added yet, should I leave this issue opened?

Thank you.
