### ISSUE TITLE
Setting the Enforcer Group type does not work

### ISSUE THREAD

**Issue by davidrosson** [aquasecurity/terraform-provider-aquasec#115]
Setting the `type` parameter for an Enforcer Group (via an `aquasec_enforcer_groups` resource) does not create the expected Enforcer Group type. Instead, regardless of what value is set for the `type` parameter, the resulting Enforcer Group is an "Aqua Enforcer" Enforcer Group.

### Terraform Version
`v1.0.11`

### Affected Resource(s)
- `aquasec_enforcer_groups`

### Expected Behavior
- Setting the `type` parameter to `host_enforcer` should create a "VM Enforcer" Enforcer Group.
- Setting the `type` parameter to `kube_enforcer` should create a "Kube Enforcer" Enforcer Group.
- Setting the `type` parameter to `micro_enforcer` should create a "Micro Enforcer" Enforcer Group.
- Setting the `type` parameter to `nano_enforcer` should create a "Nano Enforcer" Enforcer Group.

### Actual Behavior
An "Aqua Enforcer" Enforcer Group is always created.

### Root Cause
Although the `type` parameter is defined in the associated schema (in the file `aquasec/resource_enforcer_group.go`) as a `Required` field, and therefore **_must_** be specified in the Terraform resource configuration, the provided value is not actually included in the JSON that gets passed to the `hostsbatch` API; instead, the passed value of `type` is an empty string:
```
{"id":"demo1", "logicalname":"demo1", "type":"", ...}
```
This is because there is no mechanism in the `expandEnforcerGroup` function to set `enforcerGroup.Type`. As a result, any new Enforcer Group that gets created, regardless of the provided value of the `type` parameter, will automatically be an "Aqua Enforcer" Enforcer Group (with `type="agent"`), since that is apparently the Aqua Server's default. This is not only unexpected, but in the case of trying to create a different Enforcer Group type, can result in a permanent "diff" in the Terraform state.

**Comment by semyonmor** [comment]
Fixed by #117
