### ISSUE TITLE
'aquasec_enforcer_groups' does not set property 'auto_copy_secrets' when agent type is 'kube_enforcer' and resource is created for the first time

### ISSUE THREAD

**Issue by violiveira** [aquasecurity/terraform-provider-aquasec#126]
Hello,

When creating an enforcer group of agent type `kube_enforcer`, the resource is unable to set the property `auto_copy_secrets`.

After setting it to false on terraform:

`auto_copy_secrets = false`

The property is still set to `true` when checked on the console. Also, doing a terraform plan straight after terraform apply shows the output below:

```
~ resource "aquasec_enforcer_groups" "ke" {
      ~ auto_copy_secrets                              = true -> false
        id                                             = "ke"
      + logical_name                                   = "ke"
```

This shows that the property is indeed not being set by terraform.

### Terraform Version
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/aquasecurity/aquasec v0.8.11

**Comment by yossig-aquasec** [comment]
Hi @violiveira I checked the auto_copy_secrets with success, It enable\disable it from the UI.
can you please provide yours terraform file and the aqua version?

**Comment by semyonmor** [comment]
Hi @violiveira 
Any update from your side?

**Comment by violiveira** [comment]
Hi all, I have done further testing and I have found that this bug happens only once, just when the resource is created for the first time. I have updated the title of the bug.

For example, try creating the resource below:

```
resource "aquasec_enforcer_groups" "kube-enforcer" {
  group_id = "kube-enforcer"
  type = "kube_enforcer"
  description = "Kube Enforcer"
  orchestrator {
    type = "kubernetes"
    master = false
    namespace = "aqua"
  }
  logical_name = "kube-enforcer"
  gateways = [ "aqua-gateway-csp-748b689cbd-g74kx_gateway" ]

  micro_enforcer_image_name = "registry.aquasec.com/microenforcer:6.5.22093"
  kube_bench_image_name = "aquasec/kube-bench:0.6.3"
  auto_copy_secrets = false
  micro_enforcer_secrets_name = "aqua-registry"

  enforce = false
  admission_control = true
  block_admission_control = false
  micro_enforcer_injection = false
  auto_discovery_enabled = true
  auto_scan_discovered_images_running_containers = true
  auto_discover_configure_registries = true
}
```

Immediately after creating it, if you check the GUI, `show_copy_secrets` will still show `true`. If you apply it a second time, then the value is changed.

This is what I am using:

```
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/aquasecurity/aquasec v0.8.11
```

Thank you.

**Comment by yossig-aquasec** [comment]
@violiveira  I founded that this bug is in the API and I opened a bug regard it to our dev, I will update you after it resolved

**Comment by yossig-aquasec** [comment]
Jira issue: SLK-52709

**Comment by semyonmor** [comment]
@violiveira can you pls update which Aqua version are you using?

**Comment by semyonmor** [comment]
@violiveira The fix for it will be released in the next `6.5` version
and we will update you

**Comment by semyonmor** [comment]
Hey @violiveira 
The latest version `6.5` was releases last week
Can you please check if your problem was solved?

**Comment by semyonmor** [comment]
Any update?

**Comment by violiveira** [comment]
Unfortunately I will not have the chance to test it in the short-term.

I think it is fair that I close this ticket then.

Thank you for all your help with this.
