### ISSUE TITLE
No description for the parameters of the aquasec_application_scope resource

### ISSUE THREAD

**Issue by violiveira** [aquasecurity/terraform-provider-aquasec#140]
Hi all, looking at https://registry.terraform.io/providers/aquasecurity/aquasec/latest/docs/resources/application_scope

There is no description of the parameters.

I am particularly confused by the `expression` attribute as this is not mentioned on the documentation.

How does the 'expression' attribute work? 
The provided example contains: `expression = "v1 && v2"`. I guess this is an AND operation between variables 1 and 2? If that is the case, how would an 'OR' operation, look like? Maybe `v1 || v2`?

Thank you.

**Comment by ruzickap** [comment]
Unfortunately the documentation is incomplete. 

What I am usually doing is to create some object manually in Aqua GUI and then you can use `data "aquasec_application_scope"` (https://github.com/aquasecurity/terraform-provider-aquasec/blob/main/examples/data-sources/aquasec_application_scope/data-source.tf) to see the structure how it looks in Terraform...

To answer your question - yes this `v1 || v2` is correct `OR` operation...

**Comment by semyonmor** [comment]
hi @violiveira 
We started to work on improving our documentation, the part of the available variables already described in this [PR](https://github.com/aquasecurity/terraform-provider-aquasec/pull/127) and others will be added in nearest future.
Regarding your second question, @ruzickap is absolutely right
