### ISSUE TITLE
It is not possible to configure permission 'scan.read' with resource aquasec_permissions_sets

### ISSUE THREAD

**Issue by violiveira** [aquasecurity/terraform-provider-aquasec#145]
Hi all, I am configuring a new permission set via terraform and I tried to set the permission `scan.read` that relates to the following control on the UI:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/13354550/178442119-2f956c30-f9f0-4f9c-a188-a38e4408065c.png">

I have found out about the `scan.read` permission via the data source `aquasec_permissions_sets`, so this permissions seems available in the API.

However when trying to create the following resource:

```
resource "aquasec_permissions_sets" "read_only" {
  name        = "read-only"
  description = "Permission Set with Read-Only permissions"
  author      = "terraform"
  ui_access   = true
  is_super    = false
  actions = [
    "image_assurance.read",
    "image_profiles.read",
    "network_policies.read",
    "runtime_policies.read",
    "acl_policies.read",
    "dashboard.read",
    "risk_explorer.read",
    "images.read",
    "risks.host_images.read",
    "functions.read",
    "enforcers.read",
    "containers.read",
    "services.read",
    "infrastructure.read",
    "risks.vulnerabilities.read",
    "risks.benchmark.read",
    "audits.read",
    "settings.read",
    "integrations.read",
    "registries_integrations.read",
    "scan.read",
    "gateways.read",
    "consoles.read",
    "web_hook.read",
    "incidents.read",
  ]
}
```

I get the following error after trying `terraform apply` (This error does not happen during `terraform plan`, just when trying to apply):

`│ Error: Valid values for var: actions_list are ( dashboard.read, risks.vulnerabilities.read, risks.vulnerabilities.write, risks.host_images.read, risks.benchmark.read, risk_explorer.read, images.read, image_profiles.read, image_assurance.read, image_assurance.write, runtime_policies.read, runtime_policies.write, functions.read, gateways.read, secrets.read, audits.read, containers.read, enforcers.read, infrastructure.read, consoles.read, settings.read, network_policies.read, acl_policies.read,acl_policies.write, services.read, integrations.read, registries_integrations.read, web_hook.read, incidents.read )
`

By comparing the permissions from the error and the permissions I tried to configure `scan.read` is the offender. Why the provider does support scan.read if it is accepted by the API?

Thank you.

### Terraform Version
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/aquasecurity/aquasec v0.8.11

### Affected Resource(s)
- aquasec_permissions_sets

**Comment by semyonmor** [comment]
Hey @violiveira 
Please try to use our latest provider version `registry.terraform.io/aquasecurity/aquasec v0.8.12`
Your issue should be solved there
Please update if we can close this issue

**Comment by violiveira** [comment]
Yes, this issue is solved now.

Thank you for the quick response.
