### ISSUE TITLE
Can not enable Forensics options in Enforcer / Host Runtime Policy

### ISSUE THREAD

**Issue by ruzickap** [aquasecurity/terraform-provider-aquasec#163]
Hello guys.

I'm not able to enable Forensics using TF provider.

The functionality is missing for these Aqua objects: 

* Enforcers
  * Aqua Enforcer
    * Container Protection: Forensics
    * Host Protection: Forensics

and 

* Runtime Policies
  * Host policy
    * Forensics

Thanks for looking at it...

**Comment by yossig-aquasec** [comment]
@ruzickap  what version are you using?
we fixed the run time policies with release v0.8.12, and regard the enforcers we will add the fix with the next release.

**Comment by ruzickap** [comment]
Hello

The "Forensics" for the Host Runtime policy is working. Please ignore that part of the issue.

The only "Forensics part" which is not working in current version `v0.8.12` of the TF provider is the:

* Enforcers
  * Aqua Enforcer
    * Container Protection: Forensics
    * Host Protection: Forensics

Thank you for the PR #169 :-)
