### ISSUE TITLE
Provider is not proxy aware

### ISSUE THREAD

**Issue by mkilchhofer** [aquasecurity/terraform-provider-aquasec#165]
Hi there,

We are currently in the evaluation phase of security products regarding container workloads related to Kubernetes. As you know, Aquasec is only one product we are testing.
Your TF provider cannot talk from our onprem Terraform Enterprise (similar to Terraform Cloud) to your SaaS platform as the provider is not proxy aware.

### Terraform Version

```console
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/aquasecurity/aquasec v0.8.12
```

### Affected Resource(s)
All resources provided from the provider.

### Terraform Configuration Files
n/a

### Debug Output
https://gist.github.com/mkilchhofer/49a155f284975df82759cf39d1b81188

### Panic Output
n/a

### Expected Behavior
Provider is proxy aware

### Actual Behavior
Provider is not proxy aware

```log
╷
│ Error: Unable to fetch token
│ 
│   with provider["registry.terraform.io/aquasecurity/aquasec"],
│   on provider.tf line 1, in provider "aquasec":
│    1: provider "aquasec" {
│ 
│ Post "https://<REDACTED>.cloud.aquasec.com/api/v1/login": dial tcp
│ <REDACTED>:443: connect: connection timed out
```

### Steps to Reproduce
Run `terraform plan` in a restricted environment without direct internet access. Then set the commonly used proxy env vars:
- `http_proxy`
- `https_proxy`
- `no_proxy`

These variables are automatically set in our **Terraform Enterprise** (https://www.terraform.io/enterprise) instance, which is hosted Onprem.

### Important Factoids
Running on [TFE](https://www.terraform.io/enterprise).

### References

- https://github.com/parnurzeal/gorequest/issues/262

**Comment by mulan04** [comment]
Hello,

please use the the new v0.8.13 terraform-provider-aquasec
Now it correctly honours the HTTPS_PROXY variable
