### ISSUE TITLE
Release v0.8.13 seems broken - checksum list has unexpected SHA-256

### ISSUE THREAD

**Issue by mkilchhofer** [aquasecurity/terraform-provider-aquasec#171]
Hi,

We were waiting on the new release with our PR merged in (#166).

I cannot install the provider now:

```log
Initializing provider plugins...
- Finding aquasecurity/aquasec versions matching "0.8.13"...
- Finding latest version of hashicorp/vault...
- Installing aquasecurity/aquasec v0.8.13...
- Installing hashicorp/vault v3.8.0...
- Installed hashicorp/vault v3.8.0 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│ 
│ Error while installing aquasecurity/aquasec v0.8.13: checksum list has
│ unexpected SHA-256 hash
│ 7c93e6389436c553c54bb86f2c2fa062c54e758b42ac570695745fa2fc053d0e (expected
│ 21006955f4546feae3cd7502d315fb5f0faa3dbcf90175b737b972916db2bc4b)
╵
```

I got two notification mails about release v0.8.13 (so maybe you released two times with the same release number, @semyonmor?).

![image](https://user-images.githubusercontent.com/7290987/182840791-18591a40-e8f4-43e4-a518-85a405b9f6e1.png)

**Comment by semyonmor** [comment]
@mkilchhofer yes, sorry for the inconvenience, we deleted the first release
And currently you can see only the correct one

**Comment by mkilchhofer** [comment]
👍  Triggered our TFE job again and now it works :-)

**Comment by semyonmor** [comment]
Thank you for confirmation
