### ISSUE TITLE
terraform plan always shows 'update in-place' even when there are no changes to be deployed

### ISSUE THREAD

**Issue by violiveira** [aquasecurity/terraform-provider-aquasec#177]
Hi all,

After creating an enforcer group with terraform, whenever we execute `terraform plan`, regardless if we changed something or not, it shows the following:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aquasec_enforcer_groups.this will be updated in-place
  ~ resource "aquasec_enforcer_groups" "this" {
        id                                             = "enforcer"
      + logical_name                                   = "enforcer"
        # (50 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

In this case, there have been no changes to the `logical_name`, but still `plan` shows that this field is going to be updated.

This bug results in a polluted plan, which makes things harder to review 

### Affected Resource(s)
Please list the resources as a list, for example:
- aquasec_enforcer_groups

### Terraform version:
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/aquasecurity/aquasec v0.8.14

**Comment by yossig-aquasec** [comment]
Hi @violiveira  can you please share the relavant tf code part?
