### ISSUE TITLE
Resource 'aquasec_integration_registry' does not support integration via Access Delegation

### ISSUE THREAD

**Issue by violiveira** [aquasecurity/terraform-provider-aquasec#207]
Hi all,

Under Administration > Integrations of the UI, we register ECR registries via access delegation by using a cross account role:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/13354550/196695521-280eb67b-b7e7-43fa-a694-79e51878b9be.png">

By looking at the [documentation](https://registry.terraform.io/providers/aquasecurity/aquasec/latest/docs/resources/integration_registry), I see no option to provide a role ARN for access delegation and that leads me to believe that this option is not supported by the provider.

Can we please support this option as this is the most secure way to configure access to a ECR registry?

Thank you.

**Comment by KoppulaRajender** [comment]
Hi @violiveira,

We are supporting the Access Delegation in registry integration with `options {}` below is the example.

```terraform
resource "aquasec_integration_registry" "demoregistry1" {
  name = "terraform-ecr909012"
  type = "AWS"
  options {
    option = "ARNRole"
    value  = "arn:aws:iam::000000000000:role/aqua-AAAAABBBBCCCDDD-EEEEFFFFGGGG"
  }
  auto_pull = true

  url              = "us-east-1"
  auto_pull_rescan = true
  auto_cleanup = false

}
```

We will make sure to add documentation on this and also will add examples in the next release.
