### ISSUE TITLE
Add Outputs to all resources

### ISSUE THREAD

**Issue by JakeMeloche** [aquasecurity/terraform-provider-aquasec#35]
We want to be able to make new resources from the output of other resources being created

ie. when creating an Enforcer Group, an "Aqua Token" gets generated so the enforcers we deploy can be added to that group. 

Can that token be returned on the successful creation of the group so the enforcers can be deployed to the newly created group easily?

**Comment by mavericknavs** [comment]
The standard way of printing output values from the resources being created is to use the "output" clause in the Terraform script -
https://learn.hashicorp.com/tutorials/terraform/outputs?in=terraform/configuration-language&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS

Please let me know if I am missing something.

**Comment by JakeMeloche** [comment]
Not just printing out the value, but creating an object from the resource output that can be called to use an input of another resource.

Here we create a AWS S3 bucket:
```hcl
# bucket
resource "aws_s3_bucket" "jakes_data" {
  bucket = "${terraform.workspace}-jakes-data"
  acl    = "private"
  tags = var.tags
}
```
Then we use another resource that blocks all public access by taking the bucket id from the resource above.
```hcl
# Block public access
resource "aws_s3_bucket_public_access_block" "jakes_data_s3_public_access" {
  bucket = aws_s3_bucket.jakes_data.id   <======= HERE
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
```
Basically .. We want the ability to create a enforcer group and take the token and then use it in an other resource:
```hcl
enforcer_group.<Name>.enforcer_group_token
```
For example(pseudo terraform code):
```hcl
create_aqua_agent "aqua_agent" {
   name = "aqua agent"
   group_token = enforcer_group.<Name>.enforcer_group_token 
}
```
We asked that all resources to have outputs that we can use in other resources as inputs.
AWS EKS module is an example for this:
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest
As you can se they have 62 inputs (some optional and some are required) and 34 outputs that we can use as inputs in other resources

**Comment by mavericknavs** [comment]
Thanks for the inputs, I am looking into it.
