### ISSUE TITLE
Provider is not found using example

### ISSUE THREAD

**Issue by rkwa-dan** [aquasecurity/terraform-provider-aquasec#44]
Hi there,

After pulling the provider source and installing  and copying the v0.8 binary to the terraform-provider-aquasec/aquasec directory  from the example instructions. : https://github.com/aquasecurity/terraform-provider-aquasec/tree/v0.8.0#install-and-test-the-provider-locally

Version of terraform being used: 
```
 $ terraform version
Terraform v1.0.1
on darwin_amd64
```

I am not able to get the provider to work because terraform 'thinks' it should be connecting to a URL 

Error:

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding terraform-provider-aquasec/aquasec/aquasec versions matching "0.8.0"...

 Error: Failed to query available provider packages

 Could not retrieve the list of available versions for provider terraform-provider-aquasec/aquasec/aquasec: could not connect to terraform-provider-aquasec: Failed to request
 discovery document: Get "https://terraform-provider-aquasec/.well-known/terraform.json": dial tcp: lookup terraform-provider-aquasec: no such host

```
 
 Current working directory.
```
$ pwd
~daniel/aqua/terraform/terraform-provider-aquasec/examples/resources
```

Location of provider binary.
```
$ find . -name terraform-provider-aquasec -type f
./.terraform/plugins/terraform-provider-aquasec/aquasec/aquasec/0.8/darwin_amd64/terraform-provider-aquasec
```

Code block used for provider
```
terraform {
  required_providers {
    aquasec = {
      version = "0.8"
      source  = "terraform-provider-aquasec/aquasec/aquasec"
    }
  }
}
```

it seems to throw the same error, regardless of which path I use, or whether I incorporate the whole or part of the file path to the binary location

Do i have to upload the provider binary to a separate GitHub repository to make this work ?

Am I doing something wrong or the path is wrong. Please can you provide a solution or guidance.
Many thanks

**Comment by mavericknavs** [comment]
Hi,

Thr fix for this issue is already in progress and the issue will be resolved shortly.

**Comment by rkwa-dan** [comment]
Thank you - let me know when you're ready for me to test. :)

**Comment by mavericknavs** [comment]
The issue is now fixed with Aquasec Terraform provider version 0.8.1 Please test and let us know in case of any further issues.

**Comment by rkwa-dan** [comment]
Thanks for the update - What is the fix that you provided - how do I make this work ? :)

**Comment by mavericknavs** [comment]
Hi, Just update the provider version in your tf files to 0.8.1 and then try running.

**Comment by andreazorzetto** [comment]
I raised this PR to fix the block

**Comment by jerbia** [comment]
@rkwa-dan please let me know if the new build have solved the issue. I am closing the issue for now.
