### ISSUE TITLE
aqua-user resource generation error

### ISSUE THREAD

**Issue by rkwa-dan** [aquasecurity/terraform-provider-aquasec#47]
When using `0.8.1` version of the provider from hcl
tested on  `Aqua Cloud Native Security Platform 5.0.20274, built Sep 30 2020 06:40:00`
Generation of the resource  `aquasec_user` the code block appears to execute but does
 not generate a valid ID

```
resource "aquasec_user" "test-user" {
  user_id  = "terraform-user"
  password = "password"
  name     = "Terraform User"
  email    = "terraform@test.com"
  roles = [
    "Scanner",
    "Administrator"
  ]
}
```

When running terraform apply (after init and plan) and `$TF_LOG=debug set`

output appears as : 

```
Plan: 2 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aquasec_user.test-user: Creating... 
aquasec_enforcer_groups.new: Creating...
aquasec_container_runtime_policy.test: Modifying... [id=test]
aquasec_container_runtime_policy.test: Modifications complete after 1s [id=test]
╷
│ Error: user not found: terraform-user
│ 
│   with aquasec_user.test-user,
│   on main.tf line 23, in resource "aquasec_user" "test-user":
│   23: resource "aquasec_user" "test-user" {
│ 
```
No user is created and i cannot see the test user as stated in the User management part of aqua.

**Comment by lkpdev** [comment]
I'm facing similar issue with group creation.

```
module.aqua_enforcer.aquasec_enforcer_groups.new[0]: Creating...                                                                                                                  
Error: enforcer group not found: test-user
```

**Comment by mavericknavs** [comment]
Recreating the issue. Will keep this thread updated

**Comment by mavericknavs** [comment]
@lkpdev on which platform You are getting this error? On demox or higher versions?

**Comment by gurugautmm** [comment]
@mavericknavs .. Customer using 6.2.21230 aqua version.

**Comment by jerbia** [comment]
@mavericknavs any update on this?

**Comment by mavericknavs** [comment]
I am testing our module on the Platform version 6.2 and will keep everyone posted.

**Comment by andresguisado** [comment]
I am getting the same error when trying to create an enforcer group, Aqua version is also v6.2

**Comment by damicd01** [comment]
Hi,

I am getting the same issue when trying to create an enforcer group using provider version 0.8.2:

```
aquasec_user.user: Refreshing state... [id=test-user-12345]
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
  # aquasec_enforcer_groups.new will be created
  + resource "aquasec_enforcer_groups" "new" {
      + command                       = (known after apply)
      + container_activity_protection = (known after apply)
      + description                   = "Created1"
      + enforce                       = true
      + gateway_address               = (known after apply)
      + gateway_name                  = (known after apply)
      + gateways                      = [
          + "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ]
      + group_id                      = "terraform"
      + host_os                       = (known after apply)
      + id                            = (known after apply)
      + install_command               = (known after apply)
      + last_update                   = (known after apply)
      + logical_name                  = "terraform-eg"
      + network_protection            = (known after apply)
      + token                         = (known after apply)
      + type                          = "agent"
      + orchestrator {
          + master          = false
          + namespace       = "aqua"
          + service_account = "aquasa"
          + type            = "kubernetes"
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
  Enter a value: yes
aquasec_enforcer_groups.new: Creating...
Error: enforcer group not found: terraform`
```

**Comment by mavericknavs** [comment]
Hi @damicd01  - Can You please share what value is being provided in the "gateways" field in Your Terraform script?

**Comment by andresguisado** [comment]
Hi @mavericknavs , @damicd01 and I used the following values in the "gateways:

- https://XXXX-d-**gw**.cloud.aquasec.com
- XXXX-d-**gw**.cloud.aquasec.com
- XXXX-d.cloud.aquasec.com
- https://XXXX-d.cloud.aquasec.com

**None** of them worked. Thanks

**Comment by mavericknavs** [comment]
Hi @andresguisado the observation so far has been that -

1) We can create an enforcer group without a Gateway.
2) If we must provide a Gateway, the value should be a valid gateway.

Can You please try to create an Enforcer from the console and see by default what gateway is populated? And then use that gateway in Your Terraform script.

**Comment by mavericknavs** [comment]
Hello @SampadR two corrections are needed in the above user creation script - 
1) Besides password, You also need to add a confirm_password field with the same password value.
2) The password is very simple and not allowed by Aquasec portal. Please use a password which adheres to the following rules and then it will allow You to create the User -
![image](https://user-images.githubusercontent.com/10618428/142633400-e20a4740-7fc3-4477-88e8-b868224da1e2.png)

**Comment by semyonmor** [comment]
@SampadR 
did you get a chance to validate deployment accordingly to @mavericknavs comments?
is it working for you? can we close the issue?

**Comment by semyonmor** [comment]
@SampadR we are closing the issue
IF you still have some problems with the provided explanation you can open a new one
