### ISSUE TITLE
Change properties to optional / add missing properties

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/terraform-provider-aquasec#50]
Please change the below attributes in code for the aquasec_group_creation resource:

1. logical_name, gateways ==>  make it optional instead of required values, should be able to pass as terraform vars.

2. container_activity_protection, network_protection ==>  make it as an optional value instead of mandatory value

3. runtme_type, enforcer_image, syscall_enabled, sync_host_images, risk_explorer_auto_discovery ==>  these values should be added and should be optional

4. Add an attribute for forcefully removing the enforcers before deletion of the aqua group.

**Comment by shahidinvozone** [comment]
For point 1, the logical_name and gateways are set to optional and they are working fine.

For point 2 the variables are not being mapped and whenever i try to run terraform plan/apply it shows that it will set the values to false/null even though i am setting them in my main.tf file.

Also, in point 3 the variables are set to optional and they dont throw an error if they are not provided. But, setting them doesnt reflect any change on the enforcer group.

Point 4, Naveen and I are working on this and will report soon.
