### ISSUE TITLE
Add support for Kubernetes Assurance policies

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/terraform-provider-aquasec#54]
Add terraform provider management for Kubernetes Assurance policies

**Comment by ruzickap** [comment]
This would be handy to use Terraform to manage "all" Aqua policies including "Kubernetes Assurance policies"...

**Comment by ruzickap** [comment]
Are there any news about it?

**Comment by violiveira** [comment]
I just want to back this up. This feature would be warmly welcomed by us.

**Comment by violiveira** [comment]
Is this feature available? I don't see a new release of the provider.

Thank you.

**Comment by semyonmor** [comment]
Merged, but not relased yet
