### ISSUE TITLE
login structure not suitable for USE env

### ISSUE THREAD

**Issue by dbreitel** [aquasecurity/terraform-provider-aquasec#55]
Hi, 
the login  module structure is not aligned the to the USE login, it still use the CSP direct login
provider "aquasec" {
  username = "XXX@XXXX.com"
  aqua_url = "https://AQUA_SERVER"
  password = "<password>"
}
for the new SaaS there is a different procedure. different structure (/v2/signin) which cannot be changed.

**Comment by mavericknavs** [comment]
Hi @jerbia  - I do not much details about the SaaS solution and the new login structure. Can You please share some documentation/docker image that I can deploy and get the details?

**Comment by dbreitel** [comment]
Hi, 
you can find the api details here: https://cloudsploit.docs.apiary.io/#introduction/api-details
this is the request 
You need initially to access a different URL, ping me at my aquasec mail and i will send it

**Comment by mavericknavs** [comment]
Thanks @dbreitel I also got the information from Amir and Team yesterday and I have started working on it.

**Comment by mavericknavs** [comment]
Closing this issue as the changes are now live.
