### ISSUE TITLE
Terraform | Enforcer Group Creation | Some fields don't get populated

### ISSUE THREAD

**Issue by MorganTAtkins** [aquasecurity/terraform-provider-aquasec#64]
## Terraform Aquasec Provider:
https://registry.terraform.io/providers/aquasecurity/aquasec/latest/docs/resources/enforcer_groups

## Problem description:
Some variables used to create groups of Enforcers in Aqua using the plugin "Terraform Provider" (check the link above) are being correctly declared in the creation script (check the example script below) of groups of Enforcers with the desired values, however, after executing the "Terraform Provider" script, we can see that the group of Enforcers was created, but some of the fields declared through the variables present in the script are empty.

## Reproduction Steps:

-Create an EKS cluster
-Install Aqua CSP 6.5
-Install Terraform and use the Aqua Terraform Provider
https://registry.terraform.io/providers/aquasecurity/aquasec/latest/docs
-Use the example script below in order to create an Enforcer group (review the values)
-Go to the Aqua UI > Enforcer Group and check if all the fields were populated correctly according to all the variable declared.

## Affected Resource(s)
Please list the resources as a list, for example:
- aquasec_enforcer_groups

## Terraform Configuration Files
```
terraform {
required_providers {
aquasec = {
version = "0.8.4"
source  = "aquasecurity/aquasec"
}
}
}

provider "aquasec" {
username   = "administrator"
aqua_url   = "https://10.0.101.194:30443"
password   = "Lvl1supp!"
verify_tls = false
}

resource "aquasec_enforcer_groups" "jasonTest" {
gateways = []
group_id = "tf_group"
logical_name = "some_logical"
type = "agent"
enforce = "true"
image_assurance = "true"
orchestrator {
type = "kubernetes"
service_account = "aqua-sa"
namespace       = "aqua"
}
}
```

## Actual result:
1 - Some variables are being passed and populated correctly.
2 - List of variables that have been tested and are not working correctly:
service_account = "aqua-sa"
namespace  = "aqua"
enforce = "true"

## Expected results:
All variables are being passed and populated correctly the Enforcer Group's fields

**Comment by semyonmor** [comment]
@MorganTAtkins 
Look like the issue solved
Can we close it?
We will wait a few days for your response and then will close the issue
