### ISSUE TITLE
Support Create Role Mapping

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/terraform-provider-aquasec#72]
Support Create/Update/Delete of Role Mapping object (Administration -> Integrations -> SSO Authentication)

**Comment by ruzickap** [comment]
I'm looking for this feature as well...

**Comment by ruzickap** [comment]
Is there any update about it please?

**Comment by semyonmor** [comment]
> Is there any update about it please?

hey @ruzickap 
we are started to work on it
supposed to be ready next week

**Comment by chrisctl** [comment]
@semyonmor will this encompass both on-premise / ESE group role mapping and USE?

**Comment by semyonmor** [comment]
@chrisctl we are trying to add it to both ESE and USE setups
